import os

from dotenv import load_dotenv
from supabase import create_client, Client

class DataBase:
    def __init__(self):
        
        load_dotenv()

        url = os.environ.get("SUPABASE_URL")
        key = os.environ.get("SUPABASE_SECRET_KEY")

        self.supabase: Client = create_client(url, key)

    # We have two table : employee, project
    # In employee: id(autogenerated), password, name
    # In project: id(autogenerated), name, employee_id

    # GET METHOD
    # TABLE employee
    def get_employees(self):
        response = (self.supabase.table("employee").select("*").execute())
        return response.data

    def get_employee_by_id(self, id: int):
        response = (self.supabase.table("employee").select("*").eq("id", id).execute())
        return response.data

    def get_employee_by_name(self, name: str):
        response = (self.supabase.table("employee").select("*").eq("name", name).execute())
        return response.data

    # TABLE project
    def get_projects(self):
        response = (self.supabase.table("project").select("*").execute())
        return response.data

    def get_project_by_id(self, id: int):
        response = (self.supabase.table("project").select("*").eq("id", id).execute())
        return response.data

    def get_project_by_name(self, name: str):
        response = (self.supabase.table("project").select("*").eq("name", name).execute())
        return response.data

    def get_project_by_employee_id(self, employee_id: int):
        response = (self.supabase.table("project").select("*").eq("employee_id", employee_id).execute())
        return response.data

    # SET METHOD
    # TABLE employee
    def set_employee_name(self, name: str, id: int):
        response = (self.supabase.table("employee").update("name", name).eq("id", id).execute())

    def set_employee_password(self, password: str, id: int):
        response = (self.supabase.table("employee").update("password", password).eq("id", id).execute())

    # TABLE project
    def set_project_name(self, name: str, id: int):
        response = (self.supabase.table("project").update("name", name).eq("id", id).execute())

    def set_project_employee_id(self, employee_id: int, id: int):
        response = (self.supabase.table("project").update("employee_id", employee_id).eq("id", id).execute())

    # ADD METHOD
    # TABLE employee
    def add_employee(self, name: str, password: str):
        response = (self.supabase.table("employee").insert({"name": name, "password": password}).execute())

    def add_project(self, name: str, employee_id: int):
        response = (self.supabase.table("project").insert({"name": name, "employee_id": employee_id}).execute())

    # DELETE METHOD
    # TABLE employee
    def delete_employee(self, id: int):
        response = (self.supabase.table("employee").delete().eq("id", id).execute())

    # TABLE project
    def delete_project(self, id: int):
        response = (self.supabase.table("project").delete().eq("id", id).execute())
